---
name: Access Request
description: "Use this template to request access to the repository."
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this access request form!
- type: input
  id: orcid
  attributes:
    label: Please specify your ORCID.
    description: "Your ORCID is needed in order to give you access to projects."
  validations:
    required: true
---


